---
title: "Babies named Nathan and Nate 1880-2014"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Loading packages for wrangling name data
```{r setup, include=FALSE, echo=FALSE}
## install packages if necessary
list.of.packages <- c("dplyr", "ggplot2", 'plotly')
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

## load packages
library(dplyr)
library(ggplot2)
library(plotly)

## set working directoy to wherever bab names csv is located
## this needs to be done in chunk preceding any chunks which rely on working directory setting 
knitr::opts_knit$set(root.dir = '~/Desktop/codes/babynames/')
```

## Getting names data

This data comes from [kaggle.com](https://www.kaggle.com/kaggle/us-baby-names), which has collected all recorded names for children born in the United States between the years 1880-2014.

```{r names-data, warning=FALSE, echo=FALSE}
## reading in baby names csv
names <- read.csv('data/raw_data/NationalNames.csv')
```

## Limiting to boys named Nathan or Nate

```{r Nate-Nathan, warning=FALSE, echo=FALSE}

## filter out only babies with names 'Nathan' or 'Nate' and 'Male'
## this is accomplished using the filter() function available through dplyr package
dnn <- names %>% filter(Gender == 'M', Name == 'Nathan' | Name == 'Nate' | Name == 'Nathanial' | Name == 'Nathaniel' | Name == 'Nathanael')
```

## Creating interactive plot

```{r plot, warning=False, echo=FALSE}

## first create ggplot, which is a line plot with dots
p1 <- ggplot(data=dnn, aes(x=Year, y=Count, color=Name)) + 
  geom_line() + 
  geom_point() + 
  ylab('Number of babies') + 
  theme(
    plot.margin = unit(c(1,1,1,1), 'lines')
  )

## cleaner looking graph with annotations
p2 <- ggplot(data=dnn, aes(x=Year, y=Count, color=Name)) + 
  geom_line(size=1) + 
  labs(title='Baby boys named Nathan, Nate, Nathanael, Nathanial and Nathaniel',
       subtitle='United States, 1880-2014', 
       caption='Source: www.kaggle.com') + 
  ylab('Number of babies') + 
  scale_x_continuous(breaks=seq(1880,2014, by=10)) + 
  theme(
    plot.margin = unit(c(1,1,1,1), 'lines')
  )

## in order to make interactive, we will view the plot using ggplotly() function
ggplotly(p1)
p2

## you should be able to hover mouse over individual points to see count and year
## if you don't want the graph to show up inside R markdown file:
    ## click on gear aside of knit at top
    ## select 'Chuck Output in Console'
```
